enum COMMAND_ID {
    GET_BATTERY = 0,
    ARE_YOU_ALIVE = 1,
    GET_STATS = 2,
    RESET_ESTIMATED_RANGE = 3,
    RESET_TRIP_A = 4,

    SET_ODOMETER = 6,
    SAVE_PREFERENCES = 7,

    GET_FW = 9,
    PING = 10,
    TOGGLE_FRONT_LIGHT = 11,

    SET_AMPHOURS_USED_LIFETIME = 13,
    GET_VESC_MCCONF = 14,
    SET_VESC_MCCONF = 15,
    SET_AMPHOURS_CHARGED = 16,
    BACKEND_LOG = 17,
    TOGGLE_CHARGING_STATE = 18,
    TOGGLE_REGEN_BRAKING = 19,
    GET_ANALOG_READINGS = 20,
    RESET_TRIP_B = 21,
};